cask_args appdir: "/Applications"

tap "homebrew/bundle"

# A cat clone with syntax highlighting and Git integration
brew "bat"
# A matrix client for the command line
brew "cmatrix"
# Modern replacement for ls
brew "eza"
# Fuzzy finder for the command line to enhance search capabilities
brew "fzf"
# A syntax-highlighting pager for git, diff, and grep output
brew "git-delta"
# Docker client for the command line
brew "lazydocker"
# Git client for the command line
brew "lazygit"
# Media player that supports a wide range of video and audio formats
brew "mpv"
# Fast, highly customizable system info script
brew "neofetch"
# Vim-fork focused on extensibility and usability
brew "neovim"
# Node 
brew "node"
# Npm alternative
brew "pnpm"
# Rust programming language
brew "rust"
# Cross-shell prompt that is fast, customizable, and minimal
brew "starship"
# Symlink farm manager to easily manage dotfiles
brew "stow"
# fffffffff
brew "thefuck"
# Terminal multiplexer
brew "tmux"
# Tmux plugin manager
brew "tpm"
# A better cd command
brew "zoxide"
# Zsh plugin that suggests commands as you type based on history
brew "zsh-autosuggestions"
# Zsh plugin that provides syntax highlighting for the command line
brew "zsh-syntax-highlighting"

# Application switcher for macOS that mimics the Windows Alt-Tab behavior
cask "alt-tab"
# Platform for developing, shipping, and running applications in containers
cask "docker"
# Dock manager for macOS
cask "dockey"
# Firefox web browser
cask "firefox"
# Developer targeted fonts with a high number of glyphs
cask "font-jetbrains-mono-nerd-font"
# Cool font
cask "font-maple-mono"
# GPU-accelerated terminal emulator and multiplexer
cask "ghostty"
# Window manager for macOS
cask "nikitabobko/tap/aerospace"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# rofi/alfred alternative for macOS
cask "raycast"
# symbols for emojis etc
cask "sf symbols"
